export const fontOptions = [
  { id: 'system', label: 'Predeterminado / System', fontStyle: undefined },
  { id: 'inter', label: 'Inter', fontStyle: { fontFamily: 'Inter_400Regular' } },
  { id: 'lora', label: 'Lora', fontStyle: { fontFamily: 'Lora_400Regular' } },
  { id: 'jetbrains', label: 'JetBrains Mono', fontStyle: { fontFamily: 'JetBrainsMono_400Regular' } },
  { id: 'roboto', label: 'Roboto', fontStyle: { fontFamily: 'Roboto_400Regular' } },
  { id: 'lato', label: 'Lato', fontStyle: { fontFamily: 'Lato_400Regular' } },
  { id: 'montserrat', label: 'Montserrat', fontStyle: { fontFamily: 'Montserrat_400Regular' } },
  { id: 'nunito', label: 'Nunito', fontStyle: { fontFamily: 'Nunito_400Regular' } },
  { id: 'poppins', label: 'Poppins', fontStyle: { fontFamily: 'Poppins_400Regular' } },
  { id: 'quicksand', label: 'Quicksand', fontStyle: { fontFamily: 'Quicksand_400Regular' } },
  { id: 'oswald', label: 'Oswald', fontStyle: { fontFamily: 'Oswald_400Regular' } },
  { id: 'raleway', label: 'Raleway', fontStyle: { fontFamily: 'Raleway_400Regular' } },
  { id: 'ubuntu', label: 'Ubuntu', fontStyle: { fontFamily: 'Ubuntu_400Regular' } },
  { id: 'rubik', label: 'Rubik', fontStyle: { fontFamily: 'Rubik_400Regular' } },
  { id: 'work-sans', label: 'Work Sans', fontStyle: { fontFamily: 'WorkSans_400Regular' } },
  { id: 'fira-sans', label: 'Fira Sans', fontStyle: { fontFamily: 'FiraSans_400Regular' } },
  { id: 'playfair-display', label: 'Playfair Display', fontStyle: { fontFamily: 'PlayfairDisplay_400Regular' } },
  { id: 'merriweather', label: 'Merriweather', fontStyle: { fontFamily: 'Merriweather_400Regular' } },
  { id: 'eb-garamond', label: 'Eb Garamond', fontStyle: { fontFamily: 'EBGaramond_400Regular' } },
  { id: 'pt-serif', label: 'Pt Serif', fontStyle: { fontFamily: 'PTSerif_400Regular' } },
  { id: 'noto-serif', label: 'Noto Serif', fontStyle: { fontFamily: 'NotoSerif_400Regular' } },
  { id: 'libre-baskerville', label: 'Libre Baskerville', fontStyle: { fontFamily: 'LibreBaskerville_400Regular' } },
  { id: 'cormorant-garamond', label: 'Cormorant Garamond', fontStyle: { fontFamily: 'CormorantGaramond_400Regular' } },
  { id: 'crimson-text', label: 'Crimson Text', fontStyle: { fontFamily: 'CrimsonText_400Regular' } },
  { id: 'fira-code', label: 'Fira Code', fontStyle: { fontFamily: 'FiraCode_400Regular' } },
  { id: 'space-mono', label: 'Space Mono', fontStyle: { fontFamily: 'SpaceMono_400Regular' } },
  { id: 'inconsolata', label: 'Inconsolata', fontStyle: { fontFamily: 'Inconsolata_400Regular' } },
  { id: 'source-code-pro', label: 'Source Code Pro', fontStyle: { fontFamily: 'SourceCodePro_400Regular' } },
  { id: 'caveat', label: 'Caveat', fontStyle: { fontFamily: 'Caveat_400Regular' } },
  { id: 'pacifico', label: 'Pacifico', fontStyle: { fontFamily: 'Pacifico_400Regular' } },
  { id: 'dancing-script', label: 'Dancing Script', fontStyle: { fontFamily: 'DancingScript_400Regular' } },
];
