/**
 * @module themes
 * @description Catálogo de temas estéticos y tokens de color del Bullet Journal.
 *
 * Cada tema proporciona una paleta completa y coherente diseñada para journaling
 * de alta legibilidad, reduciendo la fatiga visual y respetando el espíritu
 * analógico y minimalista.
 */

export const systemLightTheme = {
  id:                   'system_light',
  name:                 'Sistema (Azul / Blanco)',
  nameEn:               'System (Blue / White)',
  isDark:               false,
  recommendedFont:      'system',
  recommendedFontLabel: 'Sistema',
  fontStyle:            undefined,
  background:           '#F4F6F9',
  cardBackground:       '#FFFFFF',
  cardCompleted:        '#F8FAFC',
  text:                 '#1E293B',
  textSecondary:        '#64748B',
  textCompleted:        '#94A3B8',
  border:               '#E2E8F0',
  primary:              '#007AFF',
  primaryBackground:    '#E6F4FE',
  tabBar:               '#FFFFFF',
  inputBackground:      '#F1F5F9',
  iconInactive:         '#64748B',
  buttonBackground:     '#CBD5E1',
  error:                '#FF3B30',
};

export const lightTheme = {
  id:                   'light',
  name:                 'Monocromo',
  nameEn:               'Monochrome',
  isDark:               false,
  recommendedFont:      'system',
  recommendedFontLabel: 'Sistema',
  fontStyle:            undefined,
  background:           '#FFFFFF',
  cardBackground:       '#FFFFFF',
  cardCompleted:        '#F5F5F7',
  text:                 '#000000',
  textSecondary:        '#666666',
  textCompleted:        '#8E8E93',
  border:               '#E5E5EA',
  primary:              '#000000',
  primaryBackground:    '#EFEFEF',
  tabBar:               '#FFFFFF',
  inputBackground:      '#F2F2F7',
  iconInactive:         '#8E8E93',
  buttonBackground:     '#D1D1D6',
  error:                '#FF3B30',
};

export const darkTheme = {
  id:                   'dark',
  name:                 'Monocromo Oscuro',
  nameEn:               'Monochrome Dark',
  isDark:               true,
  recommendedFont:      'system',
  recommendedFontLabel: 'Sistema',
  fontStyle:            undefined,
  background:           '#000000',
  cardBackground:       '#1C1C1E',
  cardCompleted:        '#121212',
  text:                 '#FFFFFF',
  textSecondary:        '#EBEBF5',
  textCompleted:        '#636366',
  border:               '#38383A',
  primary:              '#0A84FF',
  primaryBackground:    '#002E5C',
  tabBar:               '#1C1C1E',
  inputBackground:      '#2C2C2E',
  iconInactive:         '#999999',
  buttonBackground:     '#3A3A3C',
  error:                '#FF453A',
};

export const sepiaTheme = {
  id:                   'sepia',
  name:                 'Papel Moleskine',
  nameEn:               'Warm Moleskine',
  isDark:               false,
  recommendedFont:      'eb-garamond',
  recommendedFontLabel: 'EB Garamond',
  fontStyle:            { fontFamily: 'EBGaramond_700Bold' },
  background:           '#F5EFEB',
  cardBackground:       '#FCF9F5',
  cardCompleted:        '#ECE4DA',
  text:                 '#2B2118',
  textSecondary:        '#807164',
  textCompleted:        '#A49689',
  border:               '#E4D8CC',
  primary:              '#A3532C',
  primaryBackground:    '#F5E5DC',
  tabBar:               '#F5EFEB',
  inputBackground:      '#ECE3D8',
  iconInactive:         '#96887B',
  buttonBackground:     '#DECFC0',
  error:                '#B33927',
};

export const obsidianTheme = {
  id:                   'obsidian',
  name:                 'Obsidian Pizarra',
  nameEn:               'Obsidian Slate',
  isDark:               true,
  recommendedFont:      'jetbrains',
  recommendedFontLabel: 'JetBrains Mono',
  fontStyle:            { fontFamily: 'JetBrainsMono_700Bold' },
  background:           '#141416',
  cardBackground:       '#1E1E22',
  cardCompleted:        '#17171A',
  text:                 '#E8E7EC',
  textSecondary:        '#94929D',
  textCompleted:        '#5C5A65',
  border:               '#2E2D35',
  primary:              '#9D7CFF',
  primaryBackground:    '#282046',
  tabBar:               '#18181B',
  inputBackground:      '#26252C',
  iconInactive:         '#6B6976',
  buttonBackground:     '#363440',
  error:                '#E05353',
};

export const nordTheme = {
  id:                   'nord',
  name:                 'Nórdico Polar',
  nameEn:               'Arctic Nord',
  isDark:               true,
  recommendedFont:      'space-mono',
  recommendedFontLabel: 'Space Mono',
  fontStyle:            { fontFamily: 'SpaceMono_700Bold' },
  background:           '#222630',
  cardBackground:       '#2B313E',
  cardCompleted:        '#1F232C',
  text:                 '#ECEFF4',
  textSecondary:        '#96A1B4',
  textCompleted:        '#586377',
  border:               '#3A4354',
  primary:              '#88C0D0',
  primaryBackground:    '#1D333E',
  tabBar:               '#252B37',
  inputBackground:      '#333B4A',
  iconInactive:         '#6B788E',
  buttonBackground:     '#3E485B',
  error:                '#BF616A',
};

export const matchaTheme = {
  id:                   'matcha',
  name:                 'Matcha Zen',
  nameEn:               'Matcha Zen',
  isDark:               false,
  recommendedFont:      'quicksand',
  recommendedFontLabel: 'Quicksand',
  fontStyle:            { fontFamily: 'Quicksand_700Bold' },
  background:           '#EFF3EE',
  cardBackground:       '#FAFCF9',
  cardCompleted:        '#E2E9E0',
  text:                 '#1E2A21',
  textSecondary:        '#6C7D70',
  textCompleted:        '#93A296',
  border:               '#D8E1D6',
  primary:              '#3D724E',
  primaryBackground:    '#E0EFE5',
  tabBar:               '#EAF0E8',
  inputBackground:      '#E2EAE0',
  iconInactive:         '#758778',
  buttonBackground:     '#CFDCD0',
  error:                '#C04134',
};

export const asanaTheme = {
  id:                   'asana',
  name:                 'Coral Dinámico',
  nameEn:               'Dynamic Coral',
  isDark:               false,
  recommendedFont:      'rubik',
  recommendedFontLabel: 'Rubik',
  fontStyle:            { fontFamily: 'Rubik_700Bold' },
  background:           '#FAF8F5',
  cardBackground:       '#FFFFFF',
  cardCompleted:        '#F3EFEB',
  text:                 '#242529',
  textSecondary:        '#6D6E72',
  textCompleted:        '#9B9C9E',
  border:               '#ECE7E1',
  primary:              '#F06A6A',
  primaryBackground:    '#FEEEEE',
  tabBar:               '#FFFFFF',
  inputBackground:      '#F4EFEA',
  iconInactive:         '#8A8B8F',
  buttonBackground:     '#E5DFD7',
  error:                '#E53935',
};

export const todoistTheme = {
  id:                   'todoist',
  name:                 'Rubí Enfoque',
  nameEn:               'Ruby Focus',
  isDark:               false,
  recommendedFont:      'lato',
  recommendedFontLabel: 'Lato',
  fontStyle:            { fontFamily: 'Lato_700Bold' },
  background:           '#FAFAFA',
  cardBackground:       '#FFFFFF',
  cardCompleted:        '#F0F1F3',
  text:                 '#202020',
  textSecondary:        '#757575',
  textCompleted:        '#A0A0A0',
  border:               '#EEEEEE',
  primary:              '#E44234',
  primaryBackground:    '#FDEDEB',
  tabBar:               '#FFFFFF',
  inputBackground:      '#F2F3F5',
  iconInactive:         '#888888',
  buttonBackground:     '#E0E2E6',
  error:                '#C53030',
};

export const trelloTheme = {
  id:                   'trello',
  name:                 'Azul Tablero',
  nameEn:               'Ocean Board',
  isDark:               false,
  recommendedFont:      'ubuntu',
  recommendedFontLabel: 'Ubuntu',
  fontStyle:            { fontFamily: 'Ubuntu_700Bold' },
  background:           '#F4F5F7',
  cardBackground:       '#FFFFFF',
  cardCompleted:        '#EBECF0',
  text:                 '#172B4D',
  textSecondary:        '#5E6C84',
  textCompleted:        '#8993A4',
  border:               '#DFE1E6',
  primary:              '#0079BF',
  primaryBackground:    '#E6F0F8',
  tabBar:               '#FFFFFF',
  inputBackground:      '#EBECF0',
  iconInactive:         '#7A869A',
  buttonBackground:     '#D5D9E2',
  error:                '#EB5A46',
};

/** Mapa para resolución O(1) del tema por su ID de preferencia */
export const THEMES_MAP = {
  system_light: systemLightTheme,
  light:        lightTheme,
  dark:         darkTheme,
  sepia:        sepiaTheme,
  obsidian:     obsidianTheme,
  nord:         nordTheme,
  matcha:       matchaTheme,
  asana:        asanaTheme,
  todoist:      todoistTheme,
  trello:       trelloTheme,
};

/**
 * Opciones disponibles para la UI de Ajustes con información descriptiva,
 * muestras de color y tipografía de firma.
 */
export const themeOptions = [
  {
    id:                   'system',
    icon:                 'phone-portrait-outline',
    name:                 'Automático (Sistema)',
    nameEn:               'System Default',
    desc:                 'Estilo Azul / Blanco pulcro en modo claro y negro en oscuro.',
    descEn:               'Crisp Blue / White style in light mode and black in dark.',
    recommendedFont:      'system',
    recommendedFontLabel: 'Sistema',
    fontStyle:            undefined,
    swatches:             ['#F4F6F9', '#FFFFFF', '#007AFF'],
  },
  {
    id:                   'light',
    icon:                 'contrast-outline',
    name:                 'Monocromo',
    nameEn:               'Monochrome',
    desc:                 'Blanco y negro puro minimalista analógico.',
    descEn:               'Pure minimalist black and white analog aesthetic.',
    recommendedFont:      'system',
    recommendedFontLabel: 'Sistema',
    fontStyle:            undefined,
    swatches:             [lightTheme.background, lightTheme.cardBackground, lightTheme.primary],
  },
  {
    id:                   'dark',
    icon:                 'moon-outline',
    name:                 'Monocromo Oscuro',
    nameEn:               'Monochrome Dark',
    desc:                 'Negro puro OLED, blanco y gris neutro.',
    descEn:               'Pure OLED black, crisp white and neutral gray.',
    recommendedFont:      'system',
    recommendedFontLabel: 'Sistema',
    fontStyle:            undefined,
    swatches:             [darkTheme.background, darkTheme.cardBackground, darkTheme.primary],
  },
  {
    id:                   'sepia',
    icon:                 'book-outline',
    name:                 'Papel Moleskine',
    nameEn:               'Warm Moleskine',
    desc:                 'Pergamino cálido, tinta café y cuero terracota.',
    descEn:               'Warm parchment, espresso ink and terracotta accent.',
    recommendedFont:      'eb-garamond',
    recommendedFontLabel: 'EB Garamond',
    fontStyle:            { fontFamily: 'EBGaramond_700Bold' },
    swatches:             [sepiaTheme.background, sepiaTheme.cardBackground, sepiaTheme.primary],
  },
  {
    id:                   'obsidian',
    icon:                 'prism-outline',
    name:                 'Obsidian Pizarra',
    nameEn:               'Obsidian Slate',
    desc:                 'Carbón oscuro, bruma grafito y acento amatista.',
    descEn:               'Dark charcoal, graphite mist and amethyst accent.',
    recommendedFont:      'jetbrains',
    recommendedFontLabel: 'JetBrains Mono',
    fontStyle:            { fontFamily: 'JetBrainsMono_700Bold' },
    swatches:             [obsidianTheme.background, obsidianTheme.cardBackground, obsidianTheme.primary],
  },
  {
    id:                   'nord',
    icon:                 'snow-outline',
    name:                 'Nórdico Polar',
    nameEn:               'Arctic Nord',
    desc:                 'Noche polar ártica y azul glacial aurora.',
    descEn:               'Arctic polar night and glacial aurora cyan.',
    recommendedFont:      'space-mono',
    recommendedFontLabel: 'Space Mono',
    fontStyle:            { fontFamily: 'SpaceMono_700Bold' },
    swatches:             [nordTheme.background, nordTheme.cardBackground, nordTheme.primary],
  },
  {
    id:                   'matcha',
    icon:                 'leaf-outline',
    name:                 'Matcha Zen',
    nameEn:               'Matcha Zen',
    desc:                 'Verde salvia sereno, papel washi y bambú.',
    descEn:               'Serene sage green, washi paper and fresh bamboo.',
    recommendedFont:      'quicksand',
    recommendedFontLabel: 'Quicksand',
    fontStyle:            { fontFamily: 'Quicksand_700Bold' },
    swatches:             [matchaTheme.background, matchaTheme.cardBackground, matchaTheme.primary],
  },
  {
    id:                   'asana',
    icon:                 'flame-outline',
    name:                 'Coral Dinámico',
    nameEn:               'Dynamic Coral',
    desc:                 'Energía coral sobre lienzo cálido y equilibrado.',
    descEn:               'Vibrant coral energy on a warm, balanced canvas.',
    recommendedFont:      'rubik',
    recommendedFontLabel: 'Rubik',
    fontStyle:            { fontFamily: 'Rubik_700Bold' },
    swatches:             [asanaTheme.background, asanaTheme.cardBackground, asanaTheme.primary],
  },
  {
    id:                   'todoist',
    icon:                 'checkbox-outline',
    name:                 'Rubí Enfoque',
    nameEn:               'Ruby Focus',
    desc:                 'Rojo carmesí de alta productividad y contraste puro.',
    descEn:               'Crimson red with high productivity and sharp contrast.',
    recommendedFont:      'lato',
    recommendedFontLabel: 'Lato',
    fontStyle:            { fontFamily: 'Lato_700Bold' },
    swatches:             [todoistTheme.background, todoistTheme.cardBackground, todoistTheme.primary],
  },
  {
    id:                   'trello',
    icon:                 'grid-outline',
    name:                 'Azul Tablero',
    nameEn:               'Ocean Board',
    desc:                 'Azul cerúleo inspirado en flujos y tableros ágiles.',
    descEn:               'Cerulean blue inspired by agile flows and boards.',
    recommendedFont:      'ubuntu',
    recommendedFontLabel: 'Ubuntu',
    fontStyle:            { fontFamily: 'Ubuntu_700Bold' },
    swatches:             [trelloTheme.background, trelloTheme.cardBackground, trelloTheme.primary],
  },
];

/**
 * Presets tipográficos curatoriales que combinan armónicamente títulos y cuerpo de texto
 * a partir de las más de 30 fuentes disponibles en la aplicación.
 */
export const TYPOGRAPHY_PRESETS = [
  {
    id:         'editorial',
    name:       'Editorial Clásico',
    nameEn:     'Classic Editorial',
    desc:       'Playfair Display + EB Garamond',
    descEn:     'Playfair Display + EB Garamond',
    icon:       'book-outline',
    globalFont: 'eb-garamond',
    config: {
      h1:      { fontFamily: 'playfair-display', fontSize: 30, fontWeight: '700', color: null },
      h2:      { fontFamily: 'playfair-display', fontSize: 24, fontWeight: '700', color: null },
      h3:      { fontFamily: 'cormorant-garamond', fontSize: 20, fontWeight: '700', color: null },
      body:    { fontFamily: 'eb-garamond', fontSize: 16, fontWeight: '400', color: null },
      caption: { fontFamily: 'eb-garamond', fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: 'eb-garamond', fontSize: 12, fontWeight: '400', color: null },
    },
  },
  {
    id:         'manuscript',
    name:       'Diario Manuscrito',
    nameEn:     'Handwritten Journal',
    desc:       'Caveat + Lora',
    descEn:     'Caveat + Lora',
    icon:       'pencil-outline',
    globalFont: 'lora',
    config: {
      h1:      { fontFamily: 'caveat', fontSize: 34, fontWeight: '700', color: null },
      h2:      { fontFamily: 'dancing-script', fontSize: 26, fontWeight: '700', color: null },
      h3:      { fontFamily: 'caveat', fontSize: 22, fontWeight: '600', color: null },
      body:    { fontFamily: 'lora', fontSize: 16, fontWeight: '400', color: null },
      caption: { fontFamily: 'lora', fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: 'lora', fontSize: 12, fontWeight: '400', color: null },
    },
  },
  {
    id:         'hacker',
    name:       'Terminal Hacker',
    nameEn:     'Hacker Terminal',
    desc:       'JetBrains Mono + Fira Code',
    descEn:     'JetBrains Mono + Fira Code',
    icon:       'terminal-outline',
    globalFont: 'jetbrains',
    config: {
      h1:      { fontFamily: 'jetbrains', fontSize: 28, fontWeight: '700', color: null },
      h2:      { fontFamily: 'jetbrains', fontSize: 22, fontWeight: '700', color: null },
      h3:      { fontFamily: 'fira-code', fontSize: 18, fontWeight: '600', color: null },
      body:    { fontFamily: 'jetbrains', fontSize: 15, fontWeight: '400', color: null },
      caption: { fontFamily: 'fira-code', fontSize: 13, fontWeight: '500', color: null },
      micro:   { fontFamily: 'fira-code', fontSize: 11, fontWeight: '400', color: null },
    },
  },
  {
    id:         'nordic',
    name:       'Estudio Nórdico',
    nameEn:     'Nordic Studio',
    desc:       'Work Sans + Inter',
    descEn:     'Work Sans + Inter',
    icon:       'compass-outline',
    globalFont: 'inter',
    config: {
      h1:      { fontFamily: 'work-sans', fontSize: 30, fontWeight: '700', color: null },
      h2:      { fontFamily: 'montserrat', fontSize: 24, fontWeight: '700', color: null },
      h3:      { fontFamily: 'work-sans', fontSize: 20, fontWeight: '600', color: null },
      body:    { fontFamily: 'inter', fontSize: 16, fontWeight: '400', color: null },
      caption: { fontFamily: 'inter', fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: 'inter', fontSize: 12, fontWeight: '400', color: null },
    },
  },
  {
    id:         'zen',
    name:       'Zen Wabi-Sabi',
    nameEn:     'Zen Wabi-Sabi',
    desc:       'Playfair Display + Quicksand',
    descEn:     'Playfair Display + Quicksand',
    icon:       'flower-outline',
    globalFont: 'quicksand',
    config: {
      h1:      { fontFamily: 'playfair-display', fontSize: 30, fontWeight: '600', color: null },
      h2:      { fontFamily: 'quicksand', fontSize: 24, fontWeight: '700', color: null },
      h3:      { fontFamily: 'quicksand', fontSize: 20, fontWeight: '600', color: null },
      body:    { fontFamily: 'quicksand', fontSize: 16, fontWeight: '500', color: null },
      caption: { fontFamily: 'quicksand', fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: 'quicksand', fontSize: 12, fontWeight: '500', color: null },
    },
  },
  {
    id:         'poetry',
    name:       'Poesía & Ensayo',
    nameEn:     'Poetry & Essay',
    desc:       'Cormorant Garamond + Crimson Text',
    descEn:     'Cormorant Garamond + Crimson Text',
    icon:       'document-text-outline',
    globalFont: 'crimson-text',
    config: {
      h1:      { fontFamily: 'cormorant-garamond', fontSize: 32, fontWeight: '700', color: null },
      h2:      { fontFamily: 'cormorant-garamond', fontSize: 26, fontWeight: '600', color: null },
      h3:      { fontFamily: 'libre-baskerville', fontSize: 19, fontWeight: '700', color: null },
      body:    { fontFamily: 'crimson-text', fontSize: 17, fontWeight: '400', color: null },
      caption: { fontFamily: 'crimson-text', fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: 'crimson-text', fontSize: 12, fontWeight: '400', color: null },
    },
  },
  {
    id:         'default',
    name:       'Predeterminado',
    nameEn:     'System Default',
    desc:       'Tipografía nativa limpia',
    descEn:     'Clean native typography',
    icon:       'refresh-outline',
    globalFont: 'system',
    config: {
      h1:      { fontFamily: null, fontSize: 30, fontWeight: '800', color: null },
      h2:      { fontFamily: null, fontSize: 24, fontWeight: '800', color: null },
      h3:      { fontFamily: null, fontSize: 20, fontWeight: '700', color: null },
      body:    { fontFamily: null, fontSize: 16, fontWeight: '500', color: null },
      caption: { fontFamily: null, fontSize: 13, fontWeight: '600', color: null },
      micro:   { fontFamily: null, fontSize: 12, fontWeight: '400', color: null },
    },
  },
];
